services:
  - type: web
    name: event-management-system
    env: docker
    plan: free
    region: singapore
    healthCheckPath: /login
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: event-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: event-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: event-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: event-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: event-db
          property: password
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: event-db
    plan: free
    region: singapore
